// program to get a random item from an array

function getRandomItem(arr){
   const randomElement = Math.floor(Math.random() * arr.length)

   const item = arr[randomElement]

   return item
}




const array = [1, 'hello', 5, 8];

const result = getRandomItem(array);
console.log(result);


// In the above program, a random item from an array is accessed.
// A random number between 0 to array.length is generated using the Math.random() method.
// The Math.floor() returns the nearest integer value generated by Math.random().
// This random index is then used to access a random array element.